#! /bin/sh
bash ${HOME}/scripts/cambiarFondo.sh 

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'

#temporal 
bspc rule -a Aplicaciondellamadas state=floating
bspc rule -a Gnome-terminal state=floating focus=on

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Configuración del color del feedback de preselección
bspc config presel_feedback_color '#4fb9b9'


# Configuración del touchpad
xinput set-prop 10 "libinput Tapping Enabled" 1
xinput set-prop 10 "libinput Natural Scrolling Enabled" 1

killall polybar 
bash ~/.config/polybar/launch.sh --panels

picom &
lxappearance &
sxhkd
